### ISSUE TITLE
Missing script start

### ISSUE THREAD

**Issue by purplescorpion1** [dhavalCode/ai-image-generator#2]
When I run this I get missing script start. Any suggestions what is missing? Running on windows

**Comment by dhavalCode** [comment]
@purplescorpion1 now i am converting it into next JS. Will publish it soon.

**Comment by dhavalCode** [comment]
@purplescorpion1  Can you please take screenshot of problem and put it here ?

**Comment by purplescorpion1** [comment]
Here is a screenshot of what I get when I try to run it

**Comment by dhavalCode** [comment]
@purplescorpion1  A bit understanding is needed here let's connect on twitter. I will guide you.

**Comment by purplescorpion1** [comment]
Ah sorry dont have twitter - It's ok. If it's not something you can add to
your read-me file quickly for me to follow i'll have to leave it.

Thanks for the reply

**Comment by dhavalCode** [comment]
@purplescorpion1 You need to run both separately. cd client and then try to run frontend.
Same as cd server  and then try to run backend.

**Comment by purplescorpion1** [comment]
Ok think i'm getting somewhere.

So I now get
Server running at http://localhost:8080
Database Connected Successfully

When running the server


How do you run the frontend?
If I try npm run dev vite

I get 
 VITE v4.3.1  ready in 485 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

But its just a blank page at that address

If I try build or preview I get errors

**Comment by purplescorpion1** [comment]
Finally got it working - I had to copy the index.html and src into a folder called vite

Thanks for the project
